name: flutter_app_baru
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publish

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase packages:
  firebase_core: ^2.27.0
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.0
  # kalau kamu nanti mau pakai auth bisa tambahkan:
  # firebase_auth: ^4.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
