// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoqt8dMS9lt5p6zV6ZneaG82gTAKvYzwQ',
    appId: '1:540387312749:web:5c64cf04787eef323aeb64',
    messagingSenderId: '540387312749',
    projectId: 'flutter-kelompok-185e4',
    authDomain: 'flutter-kelompok-185e4.firebaseapp.com',
    storageBucket: 'flutter-kelompok-185e4.firebasestorage.app',
    measurementId: 'G-FH7ZD92G11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-2MpM4IJyeOsRV0lSaviuGeGjWXk5fZ8',
    appId: '1:540387312749:android:71ca1ae6806bc7073aeb64',
    messagingSenderId: '540387312749',
    projectId: 'flutter-kelompok-185e4',
    storageBucket: 'flutter-kelompok-185e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7-HChrb2AYq_GVGZwR6Yb2JlxGfsjpyU',
    appId: '1:540387312749:ios:7cec1e17b8c2bbfc3aeb64',
    messagingSenderId: '540387312749',
    projectId: 'flutter-kelompok-185e4',
    storageBucket: 'flutter-kelompok-185e4.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppBaru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7-HChrb2AYq_GVGZwR6Yb2JlxGfsjpyU',
    appId: '1:540387312749:ios:7cec1e17b8c2bbfc3aeb64',
    messagingSenderId: '540387312749',
    projectId: 'flutter-kelompok-185e4',
    storageBucket: 'flutter-kelompok-185e4.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppBaru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoqt8dMS9lt5p6zV6ZneaG82gTAKvYzwQ',
    appId: '1:540387312749:web:cfdf39d18e6c1aae3aeb64',
    messagingSenderId: '540387312749',
    projectId: 'flutter-kelompok-185e4',
    authDomain: 'flutter-kelompok-185e4.firebaseapp.com',
    storageBucket: 'flutter-kelompok-185e4.firebasestorage.app',
    measurementId: 'G-PCZV477C1S',
  );

}